lib/linter-rubocop.coffee
I had excluded files in my `.rubocop.yml` rules (e.g. `db/schema.rb`), but was still seeing rubocop warnings in Atom.  Passing the `--force-exclusion` argument does the trick:
> Force excluding files specified in the configuration `Exclude` even if they are explicitly passed as arguments.
=> Modify command line arguments, add force-exclusion

lib/init.coffee, lib/linter-rubocop.coffee
Enable the possibility of customising the Rubocop launch command.
This was very useful for me to be able to run Rucocop like `rvm 1.9.3 do rubocop --force-exclusion --format emacs`.
Hope this would be useful for someone else.
=> Custom launch command

index.coffee
There is a bug: 
I use rbenv, and I have rubocop-rspec installed only for one (not global) ruby version. When I'm trying to lint a file, I'm getting an error because rubocop can't load rubocop-rspec. 
This PR fixes the issue.
=> Set working directory

index.coffee
There is an issue:
I use rbenv. When I create a new file in an unexisting folder (with https://atom.io/packages/advanced-new-file for example), linter detects that unexisting folder as cwd, and rbenv can't set correct version of ruby. As a result, linter can't find rubocop and throws an error.
This PR resolves the issue by searching closest existing dir.
=> Fix cwd if file is located in unexisting dir

index.coffee
Adds 'source.ruby.chef' to the list of grammarScopes to support the [language-chef](https://github.com/darron/language-chef/) plugin.
=> Add 'source.ruby.chef' to grammarScopes

.gitignore, CHANGELOG.md, index.coffee, package.json
Just like the title says.
It's a WIP, it executes but doesn't parse at the moment.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-rubocop/72)
=> Use stdin instead of temp file

index.coffee
Specifies the linter name, allowing the `linter` package to display it if the user chooses to.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-rubocop/81)
=> Add linter name

lib/index.coffee
Makes it possible to disable running RuboCop if your project does not include a .rubocop.yml config file.
This resolves #118
=> Option to disable linter if there's no config file

package.json
Not totally sure if this is best practice, but since the styling doesn't apply in the Atom interface I thought this would be better removed.
=> Remove nonfunctional styling from description

package.json, spec/linter-rubocop-spec.js
Before this change, activation was done on Atom startup, whether or not
you actually had any Ruby files open.
With this change in place, we postpone activation until the Atom
Ruby grammar's first use.
This improves startup time of my Atom by about 24ms, thus fixing one of
the top startup time offenders according to TimeCop.
For some frame of reference, I have 87 packages installed, and Timecop
lists all packages with startup times above 5ms.
=> Improve Atom startup time

spec/fixtures/invalid_without_url.rb, spec/linter-rubocop-spec.js
RuboCop v0.46.0 added a new rule `Style/EmptyMethod` which was causing one of the specs to fail, this corrects that issue.
=> Fix specs for rubocop@0.46.0

package.json
Add `language-ruby-on-rails` and `language-chef` to the list of language packages that will trigger activation of this package when they are used.
Fixes #179.
=> Add Ruby-On-Rails and Chef Grammars to Activation

package.json
Linter-rubocop v0.5.2 is not automatically linting chef code.  Language-chef was added to the activationHooks in 0.5.2, but looks like just a typo in that change ("chec" vs. "chef"). Tested this change locally and it restores the expected behavior.
Thanks for your work on this linter - it's very helpful!
=> Fix typo for language-chef under activationHooks

src/index.js
Addresses: https://github.com/AtomLinter/linter-rubocop/pull/200/files/2688f436d0db8072a8a7066230585e654ad690bf#diff-1fdf421c05c1140f6d71444ea2b27638
=> Pass active editor from lint function

src/index.js
=> [BUGFIX] Documentation navigation regex

package.json, src/index.js
This was added as a quick fix for certain users. Unique process spawning/termination is the proper solution so getting rid of this feature as the base package has a sensible default anyway.
Essentially reverts #210
=> Remove redundant linter-timeout

package.json, spec/.eslintrc.js, spec/linter-rubocop-spec.js
Bring in `jasmine-fix` to allow the use of `async`/`await` in the specs and refactor them to take advantage of this. Note that the handling of notifications was moved to the same implementation used in `linter-eslint`. It's a more generic implementation, and properly disposes of the subscription used to grab the notifications.
=> Asyncify the specs

spec/linter-rubocop-spec.js, src/index.js
RuboCop 0.52.0 updated their format to display cop names by default in messages (https://github.com/bbatsov/rubocop/pull/5037). Since we were already showing the cop names this caused a few issues in the specs.
This disables the default forced cop names in the messages, but at the same time updates our style to match the default output of RuboCop.
Closes #254.
=> Update format for RuboCop 0.52.0

src/index.js
Fix "Object.dirname is deprecated" error from Atom Deprecation Cop
https://github.com/AtomLinter/linter-rubocop/issues/244 
ref https://github.com/AtomLinter/linter-flake8/pull/544
=> Guard invalid path (#244)

.travis.yml, package.json, src/index.js
Check the version of RuboCop and only add the `--no-display-cop-names` flag if it is v0.52.0 or higher.
Fixes #257
=> Only add --no-display-cop-names if needed

README.md, src/index.js
This fixes several related issues running with a command like `rbenv exec bundle exec rubocop`:
* #259
* `determineExecVersion` assumes that the first argument in this.command
will be a rubocop executable. I changed it to run the entire
command with `--version` on the end.
* Under rbenv/bundler, the rubocop version can vary by working directory.
I changed the `execPathVersions` cache key to include cwd.
I tested:
* Lints with the default command
* Lints with `rbenv exec bundle exec rubocop`
* Autocorrected a file
* Throws a more helpful error when determineExecVersion can't parse the output
* Ran `npm run lint`
* Ran `npm run test`. The autocorrect test timed out locally but since I couldn't get the tests passing on master either I'm going to rely on CircleCI and fix this PR if it fails …
=>  Fix #259 and related issues running with rbenv/bundler

package.json, src/index.js
- Use the `scope.name:root-scope-used` hook, specifically to avoid the need to list out the name of all the different grammar packages that provide that scope.
- Package dependencies lazy loading on Atom startup.
=> Use activationhook scope

package-lock.json, package.json, src/index.js, src/rule-helpers.js
- All rules markdown logic moved to his own module.
- We use native `fetch` to get and cache the rules markdown.
- Added an exclusion to remove the ugly `<sup>` tag from every rule documentation.
=> Rules markdown refactor

README.md
This should help `chruby` users avoid some issues that recently came up in 247 and should be a good way to close out that issue, by documenting various options.
https://github.com/AtomLinter/linter-rubocop/issues/247
=> update readme for chruby users

package.json, spec/fixtures/.rubocop.yml, spec/fixtures/lintableFiles/abc_size.rb, spec/fixtures/yml2_2/.rubocop.yml, spec/linter-rubocop-spec.js, src/index.js, src/rule-helpers.js
- It has no sense to run Rubocop with `--no-display-cop-names` option to supress the cop name in the message to interpolate it into the excerpt later with `${copName}: ${excerpt}`.
- Added function `getRubocopBaseCommand` to get the Rubocop linter base command.
- Fixed `getRuleMarkDown` when the returned URL for the offense is not an official Rubocop style guide URL.
=> Removed getCopNameArg and --no-display-cop-names

.circleci/config.yml, .travis.yml, package-lock.json, package.json
To ease the modification/contribution to publish pipeline there has been some discussion of adopting a continuous deployment system for AtomLinter packages. To accomplish this we are making use of [`semantic-release`](https://github.com/semantic-release/semantic-release) and [`@semantic-release/apm-config`](https://github.com/semantic-release/apm-config).
This pull request has been [dynamically created using a script](https://gist.github.com/keplersj/8bc7622ea741c0964d12842bfc679c5d). While the result is not perfect, it does accompish most of the grunt work of adopting continous deployment. There is some reconciliation that needs to be done before this can be merged.
Among the things needed to be reconciled, an [APM Token](https://atom.io/account) and [GitHub …
=> Initial Adoption of Continous Deployment using semantic-release

package.json
Tell Renovate to ignore the version of Ruby in the spec fixtures.
=> Make Renovate ignore fixture configs

package.json
This will hopefully fix things, verified against the configuration from [another repository](https://github.com/AtomLinter/linter-hadolint/blob/ad51cccb386505af9f5722a0114224b36e258a3e/package.json#L69-L71) that had a similar issue.
Unfortunately the only way to be sure is to merge this and see what Renovate does.
=> Make Renovate ignore fixture configs, take two

src/index.js
We ensure the compatibility of the linter with the new Rubocop 0.68.0 version.
=> fix: rubocop v0.68.0 doesn't include the cop name in the message anymore

package.json
Fixes #314, activation hooks support by grammar scope was implemented on Atom v1.30
=> Updated minimum Atom version to 1.30

package.json, src/index.js
According to https://github.com/rubocop-hq/rubocop/issues/5976 Rails department was removed from Rubocop core and extracted to a plugin, anyway this option had no effect because was removed accidentaly on e9c0319
=> Removed configuration to run Rubocop with extra Rails cops

src/rubocop/Runner.js
Added error handler to remove duplicated code.
Removed `buildExecOptions` and `isWindows` methods.
=> refactor: added error handler, removed buildExecOptions

spec/linter-rubocop-spec.js
AbcSize cop returns the abc_vector ("<assignment, branch, condition>") in the message since 0.76 so we use a regex to maintain the backward compatibility
=> ci: fixed AbcSize test with Rubocop 0.76

src/rubocop/Rubocop.js, src/rubocop/Runner.js
Fixes #366 
We extract the Rubocop config file check to the beginning of Rubocop class methods.
=> fix #633: runner methods returns null output if no rubocop config file found

spec/.eslintrc.js
/home/travis/build/AtomLinter/linter-rubocop/spec/.eslintrc.js
- 7:5   error  Strings must use singlequote
- 8:7   error  Strings must use singlequote
- 10:9   error  Unnecessarily quoted property 'devDependencies' found
- 10:9   error  Strings must use singlequote
- 10:32  error  Missing trailing comma
- 11:8   error  Missing trailing comma
- 12:6   error  Missing trailing comma
- 13:4   error  Missing trailing comma
- 14:2   error  Extra semicolon
=> ci: eslintrc prepared for Eslint v7

spec/linter-rubocop-spec.js
With Rubocop 0.89 the size has changed.
Before 0.89
`
[<3, 18, 0> 18.25/15]`
After 0.89
`
[<3, 18, 0> 18.25/17]`
=> CI Rubocop ABCSize fix
