AtomLinter/linter-rubocop

lib/init.coffee
package.json

With this I'm solving the problems related to latest Atom versions, which throw some errors with the plugin.

Solve bugs with Atom

---

lib/linter-rubocop.coffee

Fixes a deprecation to prepare for Atom 1.0.

lib: update to use dispose

---

index.coffee

strerr shouldn't be melt with the JSON output

---

README.md

* I know the issue stated 0.34, but that version didn't work for me IIRC. Please change the version string if necessary.

Add minimum rubocop version

---

README.md

Hoping this will save people time as I just bumped into this and it took me a while to find https://github.com/AtomLinter/linter-rubocop/issues/86

Update readme to include guidance for RVM users.

---

.travis.yml
appveyor.yml
circle.yml

* Adds a configuration for CircleCI
* Update the tested Ruby version to 2.3.1
* Ensure Node.js v6 is installed for _future_ linters

Update CI builds and add CircleCI

---

CHANGELOG.md

📝 Add comparing links

---

package.json
spec/linter-rubocop-spec.js
src/index.js

I am really not a fan of semicolons. The edge cases where ASI could bite you are so small and the annoyance of having to constantly append semicolons make it not worth it IMO. Pending #207

[CHORE] No more semicolons

---

package.json
src/index.js

[FEATURE] Add configurable tiemout to lint process

---

src/index.js

Addresses https://github.com/AtomLinter/linter-rubocop/pull/211#issuecomment-295333500

Unique key based on file path

---

README.md

Had a bit of trouble configuring the linter, if the README was more like this it would have made it a bit easier. :)
Thanks!

Update README.md to reflect current config settings

---

package.json
spec/linter-rubocop-spec.js
src/index.js

chore(package): update eslint-config-airbnb-base to version 11.3.1

---

README.md

Every time I show a colleague how to use this plugin I end up telling them to do this verbally, I think rbenv is now a bit more popular than RVM and the user experience seems a bit better.

Better documentation for rbenv users

---

spec/linter-rubocop-spec.js
src/index.js

Run the linter on the Gemfile as well

[FEATURE] Run linter on Gemfile as well

---

src/index.js

Implements #306 
We should not pipe contents to Rubocop `stdin` (Rubocop does not uses the cache) if the editor buffer is not modified so Rubocop would use the cache (enabled by default)

Not pipe editor contents to stdin if the editor buffer is not modified

---

src/rule-helpers.js

Fix #335 
Robocop style guide has changed from markdown to AsciiDoc, we are getting a 404 error when we try to generate the rule documentation cache. This is a breaking change from Rubocop team, the doc will not be available for older Rubocop versions, for that versions the linter will not add the rule description, so we should not have any problem with that.

fix: rule cache

---

spec/linter-rubocop-spec.js
src/index.js
src/scope-util.js

We notify the real number of corrected offenses. Added the 'Fix file with Rubocop' option to contextual menu (related to #271).

feat: fix file refactor, added fix file option to contextual menu

---

CONTRIBUTING.md
README.md

Added contributing guidelines.

docs: Create CONTRIBUTING.md

---

.github/ISSUE_TEMPLATE/feature_request.md

Added feature request issue template

docs: update issue templates

---

src/rubocop/OffenseFormatter.js
src/rubocop/helpers/doc-cache.js

Show Rubocop offense documentation without format

---

src/index.js

Rubocop initialization code cleanup.

Simplified Rubocop initialization

---

package-lock.json
package.json

This reverts commit dd6020ab6615507dba24451037deb0fd945b86b0.

Revert "ci: added patch-package dep"
